version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Assure-toi que ce port correspond à celui utilisé par ton application backend
    volumes:
      - ./backend:/app
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Assure-toi que ce port correspond à celui utilisé par ton application front-end
    volumes:
      - ./frontend:/app
